### ISSUE TITLE
Improved Wallet Handling

### ISSUE THREAD

**Issue by JingyuZ** [colonyportal/GithubColony#5]
_From @JordanEllis6809 on June 13, 2018 14:49_

For wallets there are a few different use cases we should support, as detailed here:
https://docs.ethers.io/ethers.js/html/api-wallet.html#creating-instances

We want to make sure we can support wallets that are cold wallets, wallets from other programs like Geth, and wallets from extensions like MetaMask.

Allow the user to choose what type of wallet they want to use with the dApp through a settings menu or something like that.

_Copied from original issue: JingyuZ/GithubColony#16_

**Comment by sogasg** [comment]
It seems like we are supporting what we have to for this hackathon. 

_For reference: https://github.com/JoinColony/hackathonStarter/blob/master/src/create_colony.js_

**Comment by sogasg** [comment]
It seems like we are supporting what we have to for this hackathon. 

_For reference: https://github.com/JoinColony/hackathonStarter/blob/master/src/create_colony.js_
