### ISSUE TITLE
Improved Provider Handling

### ISSUE THREAD

**Issue by JingyuZ** [colonyportal/GithubColony#7]
_From @JordanEllis6809 on June 13, 2018 14:59_

Currently we're using a localhost provider. We should also be able to support MetaMask as a provider. Allowing the user to choose through a settings menu would be nice.

Others would be nice (like public full nodes, or a local node), but for the hackathon we could require MetaMask.

Here's an example implementation:
https://dev.to/yukkurisinai/using-metamask-as-web3js-provider-2do4 

_Copied from original issue: JingyuZ/GithubColony#18_

**Comment by JingyuZ** [comment]
_From @JordanEllis6809 on June 13, 2018 14:59_

https://web3js.readthedocs.io/en/1.0/web3.html#providers

**Comment by sogasg** [comment]
Closed by https://github.com/colonyportal/GithubColony/commit/40a4ef37766be8b434c465f9ac11ff3ac90146cc

**Comment by sogasg** [comment]
Closed by https://github.com/colonyportal/GithubColony/commit/40a4ef37766be8b434c465f9ac11ff3ac90146cc
