### ISSUE TITLE
Move interactions with Colony.js (in colony.ts) out of actions folder

### ISSUE THREAD

**Issue by JingyuZ** [colonyportal/GithubColony#9]
_From @JingyuZ on June 14, 2018 7:7_

The actions, reducers, stores should be designated for redux related actions, reducers, i.e dispatch to update state and actually update state. For example `setColonyAddress` is only related to updating `address` state in component, but `fetchDomainCount` is a network request action.

We need to create a new folder like `api` or something to deal with network requests out of SPA state changes. But it's just my preference and I'm open to discussions.

_Copied from original issue: JingyuZ/GithubColony#19_

**Comment by sogasg** [comment]
The implementation was "quick and dirty" :P

I agree we should move the colony integration stuff out of actions. It's a good idea to create an API folder or something.

But do you mean that the action files should not contain async actions (that are using dispatch)? Generally, I would do something like this in the action file:

```
const fetchDomainCount = () => async (dispatch) => {
  const domainCount = await colonyAPI.getDomainCount();
  dispatch(setDomainCount(domainCount));
};

```
Do you mean that the code above should also be in another place then actions?
